PA2 : PA2.o term.o SortingList.o autocomplete.o
	g++ -o $@ PA2.o term.o SortingList.o autocomplete.o
PA2.o : PA2.cpp
	g++ -c $?
term.o : term.cpp
	g++ -c $?
SortingList.o : SortingList.cpp
	g++ -c $?
autocomplete.o : autocomplete.cpp
	g++ -c $?