Lab10 : Lab10.o term.o SortingList.o autocomplete.o
	g++ -o $@ Lab10.o term.o SortingList.o autocomplete.o
Lab10.o : Lab10.cpp
	g++ -c $?
term.o : term.cpp
	g++ -c $?
SortingList.o : SortingList.cpp
	g++ -c $?
autocomplete.o : autocomplete.cpp
	g++ -c $?